# Generated by Django 2.2.10 on 2020-07-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
