# Generated by Django 2.2.10 on 2020-07-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20200722_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='is_alive',
        ),
    ]
