# Generated by Django 2.2.10 on 2020-07-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('author_name', models.TextField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
