# Generated by Django 2.2.10 on 2020-07-22 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200721_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 22, 8, 34, 4, 753840, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='book',
            name='pages_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='update_date',
            field=models.DateField(default=None),
        ),
    ]
