# Generated by Django 2.2.10 on 2020-07-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20200722_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='update_date',
            field=models.DateField(),
        ),
    ]
