# Generated by Django 2.2.10 on 2020-07-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20200722_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
